# Generated by Django 3.2.9 on 2021-11-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('csfd_id', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('csfd_id', models.IntegerField(default=0, unique=True)),
                ('cast', models.ManyToManyField(blank=True, default=None, related_name='cast', to='quicksearch.Actor')),
            ],
            options={
                'ordering': ['csfd_id'],
            },
        ),
    ]
